Updated start script

diff --git a/islandora_microservices b/islandora_microservices
--- a/islandora_microservices
+++ b/islandora_microservices
@@ -12,14 +12,14 @@
 # Source function library.
 
 PROG="Islandora Microservices"
-PYTHON=python
+PYTHON=python26
 MICROSERVICES_PATH=/opt/islandora_microservices/
-CONFIG_FILE=/opt/islandora_microservices/config/islandora_listener.cfg
-PLUGIN_DIR=/opt/islandora_microservices/plugins_stable
+CONFIG_FILE=islandora_listener.cfg
+PLUGIN_DIR=plugins
 PID_SEARCH=`ps -ef | grep 'python' | grep 'islandora_listener' | grep $CONFIG_FILE | grep -v 'grep' | awk '{print $2}'`
 
 # *** Please make sure you change the fedora user to reflect the local setup. ***
-FEDORA_USER=microservices
+FEDORA_USER=fedora_test
 
 start () {
 	echo -n "Starting $PROG: "
@@ -27,19 +27,19 @@ start () {
 	if [ $PID_SEARCH ]; then
 		echo "$PROG is already running"
 	else
-			# start JMS as the fedora user
-			cd $MICROSERVICES_PATH
-			sudo -E -u $FEDORA_USER bash -c "env HOME=/home/microservices $PYTHON ${MICROSERVICES_PATH}islandora_listener.py -C $CONFIG_FILE -P $PLUGIN_DIR &> /dev/null &"
-			sleep 3
-			ps -ef | grep 'python' | grep 'islandora_listener' | grep $CONFIG_FILE | grep -v 'grep' >/dev/null 2>&1
-			RETVAL=$?
-			if [ $RETVAL = 0 ]; then
-				touch /var/lock/islandora_microservices
-				echo "                                          [ OK ]"
-			else
-				echo "                                          [ FAILED ]"
-			fi
-		fi
+	    # start JMS as the fedora user
+	    cd $MICROSERVICES_PATH
+	    sudo -E -u $FEDORA_USER bash -c "env HOME=/home/$FEDORA_USER $PYTHON ${MICROSERVICES_PATH}islandora_listener.py -C $CONFIG_FILE -P $PLUGIN_DIR &> /dev/null &"
+	    sleep 3
+	    ps -ef | grep 'python' | grep 'islandora_listener' | grep $CONFIG_FILE | grep -v 'grep' >/dev/null 2>&1
+	    RETVAL=$?
+	    if [ $RETVAL = 0 ]; then
+		touch /var/lock/islandora_microservices
+		echo "                                          [ OK ]"
+	    else
+		echo "                                          [ FAILED ]"
+	    fi
+	fi
 }
 
 stop () {
